config/routes.rb
Rails.application.routes.draw do
  root to: 'bookings#new'

  resources :bookings, only: [:new, :edit, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional, dependent: :destroy

  validates :starts_at, :ends_at, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  serialize :prestations, Array
  geocoded_by :address, latitude: :lat, longitude: :lng

  belongs_to :professional, required: false

  validates :email, :name, :address, :prestations, presence: true

  after_validation :geocode

  def ends_at
    @ends_at ||= starts_at + (Prestation.where(reference: prestations).sum(:duration) * 60)
  end

  def location
    @location ||= [lat, lng]
  end
end

app/models/prestation.rb
class Prestation < ApplicationRecord
end

app/models/professional.rb
class Professional < ApplicationRecord
  serialize :prestations, Array

  has_many :bookings
  has_many :appointments
  accepts_nested_attributes_for :appointments

  def handle_prestations?(booking_prestations)
    (booking_prestations - prestations).blank?
  end

  def open?(starts_at, ends_at)
    return false unless (od = opening_day(starts_at))

    starts_at = starts_at.strftime('%H:%M')
    ends_at = ends_at.strftime('%H:%M')
    Time.parse(starts_at) >= Time.parse(od['starts_at']) &&
      Time.parse(ends_at) <= Time.parse(od['ends_at'])
  end

  def opening_day(starts_at)
    day = starts_at.strftime('%A').downcase
    opening_hours.find { |o| o['day'] == day }
  end

  def not_too_far?(location)
    Geocoder::Calculations.distance_between([lat, lng], location) <= max_kilometers
  end

  def available?(starts_at, ends_at)
    appointments.all? do |a|
      starts_at >= a.ends_at || ends_at <= a.starts_at
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def edit
    @booking = Booking.find(params[:id])
    @professionals = Professional.where(id: params[:pros].map { |p| p[:id] })
  end

  def create
    @booking = Booking.new(booking_param)

    if @booking.valid?
      if (pros = FindProfessionals.call(@booking)).present?
        @booking.save!
        redirect_to edit_booking_path @booking.id, pros: pros
      else
        redirect_to new_booking_path, alert: 'Cannot find a professional at this date, sorry!'
      end
    else
      redirect_to new_booking_path, alert: @booking.errors
    end
  end

  def update
    @booking = Booking.find(params[:id])

    @booking.assign_attributes(booking_update_params)
    # TODO: move some logic to models
    @booking.professional.appointments.create!(
      starts_at: @booking.starts_at, ends_at: @booking.ends_at
    )

    if @booking.save

      redirect_to new_booking_path, notice: 'Your reservation is booked'
    else
      redirect_to new_booking_path, alert: 'Something went wrong, please retry later'
    end
  end

  private

  def booking_param
    params.permit(:email, :name, :address, :date, :time, prestations: []).tap do |p|
      p[:starts_at] = p.delete(:date) + 'T' + p.delete(:time)
    end
  end

  def booking_update_params
    params.require(:booking).permit(:professional_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/edit.html.erb
<h1>Choose your professional</h1>

<%= form_for :booking, url: booking_path(@booking.id), method: :patch, class: "nifty_form" do |f| %>
  <%= select(:booking, :professional_id) do %>
    <% @professionals.each do |pro| %>
      <%= content_tag(:option, pro.name, value: pro.id, data: { prestations: pro.prestations }) %>
    <% end %>
  <% end %>
  <%= f.submit "Book now!" %>
<% end %>

app/views/bookings/new.html.erb
<h1>Find a professional</h1>

<%= form_with url: bookings_path, class: "nifty_form" do |f| %>
  <%= label_tag :email, "Email:" %>
  <%= f.text_field :email %>
  <br/>
  <br/>
  <%= label_tag :name, "Name:" %>
  <%= f.text_field :name %>
  <br/>
  <br/>
  <%= label_tag :address, "Address:" %>
  <%= f.text_field :address %>
  <br/>
  <br/>
  <%= label_tag :date, "Date:" %>
  <%= f.date_field :date %>
  <%= label_tag :time, "Time:" %>
  <%= f.time_field :time %>
  <br/>
  <br/>
  <%= label_tag :prestations, "Prestations:" %>
  <br/>
  <br/>
  <% Prestation.pluck(:reference).each do |prestation| %>
    <li>
      <%= check_box_tag 'prestations[]', prestation %>
      <%= h prestation.humanize %>
    </li>
  <% end %>
  <br/>
  <%= f.submit "Find" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Wecasa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <style type="text/css">
.alert-success{
  color: green;
}
  .alert-danger{
    color: red;
  }
    </style>

    <%= yield %>
  </body>
</html>